// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1b199MXGQRdbnmPMp3EAYQ9jZ9qSksQk',
    appId: '1:370151178669:web:bac322418721589159a124',
    messagingSenderId: '370151178669',
    projectId: 'chronocancerai',
    authDomain: 'chronocancerai.firebaseapp.com',
    storageBucket: 'chronocancerai.firebasestorage.app',
    measurementId: 'G-XJJ3LQJNMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtFg_dh6aZFUuV0t-srsvb0RfGHdy3X2w',
    appId: '1:370151178669:android:e7de6f7ea06c89a259a124',
    messagingSenderId: '370151178669',
    projectId: 'chronocancerai',
    storageBucket: 'chronocancerai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT4BmTuRZwAreYXRARzAs38PlUJorrM8M',
    appId: '1:370151178669:ios:0cabaa82e526266359a124',
    messagingSenderId: '370151178669',
    projectId: 'chronocancerai',
    storageBucket: 'chronocancerai.firebasestorage.app',
    iosBundleId: 'com.example.chronocancerAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT4BmTuRZwAreYXRARzAs38PlUJorrM8M',
    appId: '1:370151178669:ios:0cabaa82e526266359a124',
    messagingSenderId: '370151178669',
    projectId: 'chronocancerai',
    storageBucket: 'chronocancerai.firebasestorage.app',
    iosBundleId: 'com.example.chronocancerAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1b199MXGQRdbnmPMp3EAYQ9jZ9qSksQk',
    appId: '1:370151178669:web:007cb7553048f0de59a124',
    messagingSenderId: '370151178669',
    projectId: 'chronocancerai',
    authDomain: 'chronocancerai.firebaseapp.com',
    storageBucket: 'chronocancerai.firebasestorage.app',
    measurementId: 'G-CKTSX5LB8V',
  );
}
